<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 08 Apr 2019 11:13:39 -0400
 */

$conf['title'] = 'TIDIRH 2018';
$conf['start'] = 'home';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['maxseclevel'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,revisions,register,edit';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['target']['media'] = '_blank';
$conf['subscribers'] = 1;
$conf['mailfrom'] = 'amann@scgcorp.com';
$conf['plugin']['disableactionsbygroup']['disableactionsbygroup'] = 'admin:;author:;user:edit,backlink,revisions';
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['wikisyntaxok'] = 0;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['disqus']['shortname'] = 'TIDIRH';
$conf['plugin']['groupmail']['default'] = 'amann@scgcorp.com';
$conf['plugin']['smtp']['smtp_host'] = 'mail.scgcorp.com';
$conf['plugin']['twofactor']['enable'] = 1;
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login';

// end auto-generated content
